### ISSUE TITLE
Sphinx Documentation Broken

### ISSUE THREAD

**Issue by ljchang** [ljchang/neurolearn#19]
We need to figure out why the sphinx autodoc stopped working on readthedocs and also to update the restructured text templates for all of the new modules.

**Comment by ejolly** [comment]
So in the conf.py file that live in the docs directory, the `MOCK_MODULES` list will need to be updated with every new module that neurolearn imports anywhere in its code. I just updated it based on sphinx error messages for now, but it'll have to be something folks stay on top of for future. Kind of a pain and not sure if there is a way around this since mocking needs to happen to maintain compatibility with packages that depend on C and the readthedocs. 

I can build with auto-docs locally and everything seems to be fine, but I'm not sure if your repo webhook is working with read the docs; the link from the README doesn't seem to show any updates. I can't check the status of the documentation building on RTD without the account information though.

**Comment by ejolly** [comment]
Forgot to mention that on line 18 of nltools/analysis.py:
 `__all__ = ['Predict','apply_mask','ROC']` `ROC` doesn't seem to be used anywhere. Sphinx throws a warning but it shouldn't affect building docs.

**Comment by ljchang** [comment]
Awesome!  thanks @ejolly.  Most things seem to be working.  There are a few modules that need their documentation updated so that it builds correctly.  But readthedocs seems to be working again.   Next we need to add more tests!
